
  // Generated by https://quicktype.io

/*   export interface Orders {
    orders: Order[];
  } */

  export interface Order {
    id: number;
    name: string;
    email: string;
    phone: number;
    country: string;
    city: string;
    address: string;
    pincode: number;
    products: Product[];
  }

  export interface Product {
    name: string;
    qty: number;
    price: number;
    total: number;
  }
